(ns cljs-react-material-ui.elements
  (:require [cljs-react-material-ui.core :as m]))

(def tags
  '[
    AppBar,
    AppCanvas,
    AutoComplete,
    Avatar,
    Badge,
    BeforeAfterWrapper,
    Card,
    CardActions,
    CardExpandable,
    CardHeader,
    CardMedia,
    CardText,
    CardTitle,
    Checkbox,
    CircularProgress,
    ClearFix,
    DatePicker,
    DatePickerDialog,
    Dialog,
    Divider,
    DropDownIcon,
    DropDownMenu,
    EnhancedButton,
    FlatButton,
    FloatingActionButton,
    FontIcon,
    GridList,
    GridTile,
    IconButton,
    IconMenu,
    LeftNav,
    LinearProgress,
    List,
    ListDivider,
    ListItem,
    Menu,
    MenuItem,
    Overlay,
    Paper,
    Popover,
    RadioButton,
    RadioButtonGroup,
    RaisedButton,
    RefreshIndicator,
    Ripples,
    SelectField,
    SelectableContainerEnhance,
    Slider,
    SvgIcon,
    Styles,
    Snackbar,
    Tab,
    Tabs,
    Table,
    TableBody,
    TableFooter,
    TableHeader,
    TableHeaderColumn,
    TableRow,
    TableRowColumn,
    Toggle,
    ThemeWrapper,
    TimePicker,
    TextField,
    Toolbar,
    ToolbarGroup,
    ToolbarSeparator,
    ToolbarTitle,
    Tooltip
    ])

(defmacro generate-mui-el-fns [fname]
  `(m/generate-mui-dom-fns ~fname ~tags))

(comment
  (macroexpand `(generate-mui-el-fns "create-mui-el")))